# Makefile to compare bubble and quick sort

SRCS := $(bubblesort.c quicksort.c);

all: quick bubble

quick:  
	gcc -o quick quicksort.c

bubble: 
	gcc -o bubble bubblesort.c

clean:
	rm bubble
	rm quick
